server:
  port: 12345

spring:
  datasource:
    url: jdbc:mysql://116.62.191.135:3306/cat_shop_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123123asd
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 116.62.191.135
    port: 6379
    password: 1106@CatKittyRedis
    database: 1
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null

minio:
  baseUrl: http://itcat.top:9000
  endpoint: http://116.62.191.135:9000 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: catminio #访问的key
  secretKey: catminio #访问的秘钥

logging:
  level:
    root: info
    top.itcat.mall: debug

logstash:
  host: localhost
  enableInnerLog: false